# Generated by Django 5.1.3 on 2024-11-09 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='club_panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('club_name', models.CharField(choices=[('BUCC', 'BUCC'), ('BUCS', 'BUCS'), ('BUET', 'BUET'), ('BUFT', 'BUFT'), ('BUIS', 'BUIS'), ('BUPC', 'BUPC'), ('BUPH', 'BUPH'), ('BUPES', 'BUPES'), ('BUPES', 'BUPES'), ('BUP', 'BUP'), ('BUSS', 'BUSS')], default='BUCC', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
