# Generated by Django 5.1.3 on 2024-11-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oca', '0002_room_event_communication_budgetrequest_roombooking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='event',
        ),
        migrations.AlterField(
            model_name='club_panel',
            name='club_name',
            field=models.CharField(max_length=50),
        ),
    ]
